server:
  port: 80
security:
  user:
    name: test
    password: test
redis:
  master:
    name: master-dev
  password: wIvJt@_redis
  sentinal:
    node1:
      host: 192.168.11.29
      port: 26001
    node2:
      host: 192.168.11.32
      port: 26001
    node3:
      host: 192.168.11.20
      port: 26001
db:
  url: jdbc:mysql://120.25.73.72:3306/oauth2
  username: xiaobing
  password: 8541868