db:
  url: jdbc:mysql://120.25.73.72:3306/oauth2
  username: xiaobing
  password: 8541868
security:
  oauth2:
    resource:
      token-info-uri: http://localhost/oauth/check_token
      id: testResource
    client:
      client-id: client
      client-secret: secret
